---
- name: Check available package updates on Linux systems
  hosts: all
  gather_facts: yes 
  become: yes

  tasks:
    - name: Check for available updates (RHEL/CentOS)
      command: yum check-update
      register: update_output
      changed_when: false
      failed_when: update_output.rc not in [0, 100]
      become: yes


    - name: Show available updates (RHEL/CentOS)
      ansible.builtin.debug:
        var: yum_updates.stdout_lines
      when: ansible_facts['os_family'] == "RedHat"

    - name: Check for available updates (Ubuntu/Debian)
      ansible.builtin.shell: apt list --upgradable
      register: apt_updates
      changed_when: false
      when: ansible_facts['os_family'] == "Debian"

    - name: Show available updates (Ubuntu/Debian)
      ansible.builtin.debug:
        var: apt_updates.stdout_lines
      when: ansible_facts['os_family'] == "Debian"

