- name: Build dynamic inventory from input
  hosts: localhost
  gather_facts: no
  vars:
    myhosts: "{{ target_hosts.split(',') }}"
  tasks:
    - name: Add input hosts to dynamic group
      add_host:
        name: "{{ item | trim }}"
        groups: dynamic_targets
      loop: "{{ myhosts }}"

- name: Run tasks on dynamic hosts
  hosts: dynamic_targets
  become: yes
  gather_facts: yes
  vars:
    user_shell: "/bin/bash"
    user_comment: "{{ full_name }} - {{ user_dept }}"
    extra_group: "{{ additional_group | default('') }}"
  tasks:
    - name: Ping host
      ping:

    - name: Create user with comment and optional group
      user:
        name: "{{ user_name }}"
        shell: "{{ user_shell }}"
        comment: "{{ user_comment }}"
        groups: "{{ extra_group if extra_group != '' else omit }}"
        append: yes
        state: present

    - name: Ensure user has a home directory
      file:
        path: "/home/{{ user_name }}"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0755'
