- name: Create dynamic hosts and delete users
  hosts: localhost
  gather_facts: no
  vars:
    myhosts: "{{ target_hosts.split(',') }}"
    delete_users: "{{ user_name.split(',') }}"
  tasks:

    - name: Add input hosts to dynamic group
      add_host:
        name: "{{ item | trim }}"
        groups: dynamic_targets
      loop: "{{ myhosts }}"

- name: Delete users on dynamic hosts
  hosts: dynamic_targets
  become: yes
  gather_facts: no
  vars:
    delete_users: "{{ user_name.split(',') }}"
  tasks:

    - name: Ensure users are absent
      user:
        name: "{{ item | trim }}"
        state: absent
        remove: yes
      loop: "{{ delete_users }}"
