- name: Build dynamic inventory from input
  hosts: localhost
  gather_facts: false
  vars:
    myhosts: "{{ target_hosts.split(',') }}"
  tasks:
    - name: Add input hosts to dynamic group
      add_host:
        name: "{{ item | trim }}"
        groups: dynamic_targets
      loop: "{{ myhosts }}"

- name: Create user on dynamic hosts (with optional group and comment)
  hosts: dynamic_targets
  become: true
  gather_facts: false
  vars:
    new_username: "{{ user_name }}"
    # Combine Full Name and Department into the comment field
    user_comment: "{{ full_name | default('') }} - {{ department | default('') }}"
    extra_group: "{{ additional_group | default('') }}"
  tasks:
    - name: Create user and add to extra group if specified
      user:
        name: "{{ new_username }}"
        shell: /bin/bash
        comment: "{{ user_comment }}"
        # Only pass 'groups' when extra_group is non-empty
        groups: "{{ extra_group if extra_group != '' else omit }}"
        append: yes
        state: present

    - name: Ensure home directory exists
      file:
        path: "/home/{{ new_username }}"
        state: directory
        owner: "{{ new_username }}"
        group: "{{ new_username }}"
        mode: '0755'
