- name: Build dynamic inventory from input
  hosts: localhost
  gather_facts: no
  vars:
    myhosts: "{{ target_hosts.split(',') }}"
  tasks:
    - name: Add input hosts to dynamic group
      add_host:
        name: "{{ item | trim }}"
        groups: dynamic_targets
      loop: "{{ myhosts }}"

- name: Delete users on dynamic hosts
  hosts: dynamic_targets
  become: yes
  gather_facts: no
  vars:
    delete_users: "{{ user_name.split(',') }}"
  tasks:
    - name: Delete each user if present (force removal of mail spool)
      user:
        name: "{{ item | trim }}"
        state: absent
        remove: yes      # removes home dir + mail spool
        force: yes       # forces removal even if ownership mismatch
      loop: "{{ delete_users }}"
