- name: Build dynamic inventory from input
  hosts: localhost
  gather_facts: false
  vars:
    myhosts: "{{ target_hosts.split(',') }}"
  tasks:
    - name: Add input hosts to dynamic group
      add_host:
        name: "{{ item | trim }}"
        groups: dynamic_targets
      loop: "{{ myhosts }}"

- name: Create user on remote host (with/without extra group)
  hosts: dynamic_targets
  become: true
  gather_facts: false
  vars:
    new_username: "{{ user_name }}"
    user_comment: "{{ full_name | default('') }} {{ department | default('') }}"
    extra_group: "{{ additional_group | default('') }}"
  tasks:
    - name: Create user when an extra group is specified
      user:
        name: "{{ new_username }}"
        shell: /bin/bash
        comment: "{{ user_comment }}"
        groups: "{{ extra_group }}"
        append: yes
        state: present
      when: extra_group != ""

    - name: Create user when no extra group is specified
      user:
        name: "{{ new_username }}"
        shell: /bin/bash
        comment: "{{ user_comment }}"
        state: present
      when: extra_group == ""

    - name: Ensure home directory exists
      file:
        path: "/home/{{ new_username }}"
        state: directory
        owner: "{{ new_username }}"
        group: "{{ new_username }}"
        mode: '0755'
